### ISSUE TITLE
Complex Recipe Search

### ISSUE THREAD

**Issue by ddsky** [johnwmillr/SpoonacularAPI#6]
Hey, David from spoonacular here. Just wanted to let you know that we have a more thorough documentation now https://spoonacular.com/food-api/docs and the complex recipe search endpoint has been revisited. There are quite some new functionalities that you might find worth checking out and maybe adding to this project: https://spoonacular.com/food-api/docs#Search-Recipes-Complex (e.g. search within title)

**Comment by johnwmillr** [comment]
Thanks for the heads up, David! The updated documentation looks really good. I'd be happy to add support for the new endpoints, I'll try to make time this week to update the package.

**Comment by johnwmillr** [comment]
@ddsky the PR #7 switches to the Spoonacular API and adds support for the `search recipes complex` method. Thanks for letting me know about the changes!
