### ISSUE TITLE
Update to work with the meal planner?

### ISSUE THREAD

**Issue by Braden50** [johnwmillr/SpoonacularAPI#8]
I love your wrapper and it is extremely useful, but I was wondering if you would ever be interested in adding new user requests. I can't seem to figure out how to work with the meal plan endpoints and your wrapper was the crutch I needed here lol.

**Comment by ddsky** [comment]
Hey @Braden50 could you elaborate on what your exact problem is and what you need?

**Comment by Braden50** [comment]
Thanks for your reply! Currently I am working on making a personalized
automated meal planner. I am using the wrapper here:
https://pypi.org/project/spoonacular/ (which seems to be John Miller's
version), but this wrapper hasn't been updated in a bit, and is missing all
of the user-specific endpoints (not sure if these are new features or not).
I am new to REST API, but I am trying to fill in the gaps here to help me
with my app by updating the wrapper accordingly.

The problem I am running into is that I can't seem to get any of the user
requests to work, Like even the connect_user endpoint is not working for
me. My code below is returning a 405 error message and any attempt to
change or reach the meal planner returns a 401 error response

con_url = 'https://api.spoonacular.com/users/connect'
args = {
    'apiKey': SECRET_KEY,
    'username': USERNAME,
}
us_hash = requests.get(con_url, args)
print(us_hash.text)


It's quite possible that I just have no idea what I'm doing. In the
meantime, I've been refining my knowledge of RESTful APIs and might end up
finding out how to fix the errors that way. The work you've done on the
wrapper is amazingly helpful though, and I wanna acknowledge how
inexperienced users like me really appreciate these kinds of things.

**Comment by ddsky** [comment]
@Braden50 yes so to clarify, I'm working on the actual API and @johnwmillr created this super useful wrapper. The meal planning endpoints are indeed new and we would have to see whether John would update wrapper.

I'm not really fluent in python so I can't be of much help. However, the 405 error leads me to believe you are not sending the correct request type, i.e. POST instead of GET or vice versa. The connect user for example should be a POST request and you write ` requests.get ` ... maybe there is something like `requests.post`?

**Comment by johnwmillr** [comment]
Thank you, @ddsky! I'm a bit busy at the moment but would love to add in the meal planning endpoints when I have time. @Braden50, if you make any progress with them, feel free to open a PR.

**Comment by Braden50** [comment]
Lmao yeah maybe that's it @ddsky. I made that switch and a couple more and am now running into a 405 error with all my user related-commands, so I'm probably just missing one thing. I'll keep trying. It also seems that they might be currently upgrading their infrastructure. I'll let you guys know if I end up updating the wrapper entirely.
